feat(hydro_lang): use marker trait to improve error messages for wrong ordering / retries (#2595)
Old Error Message:
```
error[E0599]: the method `enumerate` exists for struct `hydro_lang::prelude::Stream<{integer}, hydro_lang::prelude::Process<'a, P1>, hydro_lang::prelude::Bounded, hydro_lang::live_collections::stream::NoOrder>`, but its trait bounds were not satisfied
 --> tests/compile-fail-stable/non_commutative.rs
  |
  |       let _ = p1.source_iter(q!(0..10)).weaken_ordering::<NoOrder>().enumerate();
  |                                                                      ^^^^^^^^^ method cannot be called due to unsatisfied trait bounds
  |
 ::: src/live_collections/stream/mod.rs
  |
  | / pub struct Stream<
  | |     Type,
  | |     Loc,
  | |     Bound: Boundedness = Unbounded,
  | |     Order: Ordering = TotalOrder,
  | |     Retry: Retries = ExactlyOnce,
  | | > {
  | |_- doesn't satisfy `_: Iterator`
  |
  = note: the following trait bounds were not satisfied:
          `hydro_lang::prelude::Stream<{integer}, hydro_lang::prelude::Process<'a, P1>, hydro_lang::prelude::Bounded, hydro_lang::live_collections::stream::NoOrder>: Iterator`
          which is required by `&mut hydro_lang::prelude::Stream<{integer}, hydro_lang::prelude::Process<'a, P1>, hydro_lang::prelude::Bounded, hydro_lang::live_collections::stream::NoOrder>: Iterator`
```

New Error Message:
```
error[E0277]: The input stream must be totally-ordered (`TotalOrder`), but has order `hydro_lang::live_collections::stream::NoOrder`. Strengthen the order upstream or consider a different API.
 --> tests/compile-fail-stable/non_commutative_operator.rs:7:68
  |
7 |     let _ = p1.source_iter(q!(0..10)).weaken_ordering::<NoOrder>().enumerate();
  |                                                                    ^^^^^^^^^ required for this call
  |
  = help: the trait `IsOrdered` is not implemented for `hydro_lang::live_collections::stream::NoOrder`
  = note: To intentionally process the stream with a non-deterministic (shuffled) order of elements, use `.assume_ordering`.
note: required by a bound in `hydro_lang::prelude::Stream::<T, L, B, O, R>::enumerate`
 --> src/live_collections/stream/mod.rs
  |
  |     pub fn enumerate(self) -> Stream<(usize, T), L, B, O, R>
  |            --------- required by a bound in this associated function
  |     where O: IsOrdered, R: IsExactlyOnce {
  |              ^^^^^^^^^ required by this bound in `Stream::<T, L, B, O, R>::enumerate`
```

Only implemented for `enumerate` for now because this is not a breaking
change. Will follow-up to expand its usage to all other stream
operators.